### ISSUE TITLE
Android App not working after Main Activity

### ISSUE THREAD

**Issue by manavgupta0910** [Quintor/StudyBitsWallet#15]
When i am clicking the university image it redirects to a blank page because it is not getting any data to print or go further.
Can you please explain me the whole process in which the App is working so that i can get along with this.
I have Execute you docker compose also for the back end and as well as the seeder also.

**Comment by pimotte** [comment]
It's easiest to follow along with the scenario test, this can be found here: https://github.com/Quintor/StudyBitsWallet/blob/1175183a6ccde986b0acbe8bd553b75f229bf25d/app/src/androidTest/java/nl/quintor/studybits/studybitswallet/ScenarioTest.java

The first step is to click a "connection link". 

Here you can find how it's constructed: https://github.com/Quintor/StudyBitsWallet/blob/c8d41991324e41330aad500eb82ec96def1faadd/app/src/main/java/nl/quintor/studybits/studybitswallet/TestConfiguration.java

What I personally do, is to create a jsfiddle with the links, and then click those. [this one](https://jsfiddle.net/qaLw2o4y/2/) should work if you change the ip to your computers ip address.

**Comment by manavgupta0910** [comment]
Thanks for the help:- 
I also want to know that the second agent Gent is not getting Up. Can you tell me how to make it working 
And second the intent in the main Application is not passed which is passed in Test scenario before going to the university Activity page

**Comment by manavgupta0910** [comment]
I am able to resolve the GENT  issue but now while i am running the Scenario Test I am facing an issue in the step where it finds the Msc Marketing in the Exchange Position Activity.
There is not data displayed like MSc Marketing on that Page while the page is loaded.
Can you tell me that how to solve this issue or i am missing some data which is to be given in the application 
And the Second issue of the above

**Comment by pimotte** [comment]
For either issue, are there any errors in the logs?

**Comment by manavgupta0910** [comment]
Yes, here is the log for the above error
android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "MSc Marketing"
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:88)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:51)
at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:312)
at android.support.test.espresso.ViewInteraction.check(ViewInteraction.java:297)
at nl.quintor.studybits.studybitswallet.ScenarioTest.fullScenarioTest(ScenarioTest.java:147)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at android.support.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:129)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by manavgupta0910** [comment]
I have debugg the app also the item is getting null from the ExchangePositionFragment Activity may that's why the data is not displaying on the screen.
Can you look and tell me where the problem is in actual

**Comment by pimotte** [comment]
And what do the docker-compose logs show?

**Comment by manavgupta0910** [comment]
There is no error in docker compose logs

**Comment by pimotte** [comment]
Can you save the entire log to a file and upload it somewhere?

**Comment by manavgupta0910** [comment]
Here is the log file
[logs.txt](https://github.com/Quintor/StudyBitsWallet/files/3599994/logs.txt)

**Comment by manavgupta0910** [comment]
Anything else do you want ??

**Comment by pimotte** [comment]
In the logs you can see that the university_agent_gent indeed does return an empty array for exchange positions. Are you running the tests with a freshly started docker-compose? Without using the exchange position that's pre-seeded?

**Comment by manavgupta0910** [comment]
No I am not running the test with the freshly started docker-compose. Well i try that now
